"""Integration test: intraday-trader → QEE targets.json handoff.

Validates that targets generated by an intraday-style TargetExporter are
correctly consumed by QEE's read_targets_json, write_targets_json, and
facade.execute() dry-run paths.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any

import pytest

from quant_execution_engine.facade import QEEFacade


# ------------------------------------------------------------------
# Intraday-style targets fixture (simulates TargetExporter output)
# ------------------------------------------------------------------


def _make_intraday_targets(
    *,
    symbol: str = "AAPL",
    market: str = "US",
    signal: str = "BUY",
    target_quantity: int = 10,
    signal_price: float = 198.32,
    strategy: str = "mean_reversion_zscore",
) -> list[dict[str, Any]]:
    """Simulate what intraday-trader's TargetExporter would produce."""
    return [
        {
            "symbol": symbol,
            "market": market,
            "target_quantity": target_quantity if signal == "BUY" else 0,
            "metadata": {
                "strategy": strategy,
                "signal": signal,
                "signal_price": signal_price,
            },
        }
    ]


# ------------------------------------------------------------------
# Tests
# ------------------------------------------------------------------


class TestIntradayTargetsHandoff:
    """Round-trip: intraday-style dicts → QEE TargetEntry → JSON → read back."""

    def test_buy_signal_produces_valid_target_entry(self) -> None:
        """A BUY signal with target_quantity=10 should parse without error."""
        targets = _make_intraday_targets(signal="BUY", target_quantity=10)
        facade = QEEFacade(broker_name="local-dry-run")
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "targets.json"
            result = facade.export_targets_json(targets, path)
            assert result.exists()
            doc = facade.read_targets_json(path)
            assert len(doc.targets) == 1
            entry = doc.targets[0]
            assert entry.symbol == "AAPL"
            assert entry.market == "US"
            assert entry.target_quantity == 10
            assert entry.metadata["signal"] == "BUY"

    def test_close_signal_produces_zero_quantity(self) -> None:
        """A CLOSE signal should produce target_quantity=0."""
        targets = _make_intraday_targets(signal="CLOSE", target_quantity=0)
        facade = QEEFacade(broker_name="local-dry-run")
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "targets.json"
            facade.export_targets_json(targets, path)
            doc = facade.read_targets_json(path)
            assert doc.targets[0].target_quantity == 0

    def test_targets_json_roundtrip_preserves_metadata(self) -> None:
        """Metadata fields survive JSON serialization round-trip."""
        targets = _make_intraday_targets(
            signal="BUY",
            signal_price=201.45,
            strategy="ema_crossover",
        )
        facade = QEEFacade(broker_name="local-dry-run")
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "targets.json"
            facade.export_targets_json(targets, path)
            raw = json.loads(path.read_text(encoding="utf-8"))
            meta = raw["targets"][0]["metadata"]
            assert meta["strategy"] == "ema_crossover"
            assert meta["signal"] == "BUY"
            assert meta["signal_price"] == 201.45

    def test_targets_json_includes_source_and_asof(self) -> None:
        """The exported file carries source and asof fields."""
        targets = _make_intraday_targets()
        facade = QEEFacade(broker_name="local-dry-run")
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "targets.json"
            facade.export_targets_json(
                targets, path, source="intraday-trader", asof="2026-06-22T15:30:00Z"
            )
            raw = json.loads(path.read_text(encoding="utf-8"))
            assert raw["source"] == "intraday-trader"
            assert raw["asof"] == "2026-06-22T15:30:00Z"
            assert "targets" in raw

    def test_rejects_negative_target_quantity(self) -> None:
        """QEE must reject negative quantities (short not supported)."""
        targets = [
            {"symbol": "AAPL", "market": "US", "target_quantity": -5},
        ]
        facade = QEEFacade(broker_name="local-dry-run")
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "targets.json"
            # export_targets_json calls write_targets_json which passes
            # through _entry_from_obj -> TargetEntry(...), so validation fires.
            with pytest.raises(ValueError, match="cannot be negative"):
                facade.export_targets_json(targets, path)

    def test_local_dry_run_execute_does_not_submit_orders(self) -> None:
        """Dry-run against local-dry-run should return zero orders (no positions)."""
        targets = _make_intraday_targets()
        facade = QEEFacade(broker_name="local-dry-run")
        result = facade.execute(targets, dry_run=True)
        assert result.error is None
        assert result.dry_run is True
        # local-dry-run starts with empty account, so no orders to rebalance
        assert result.order_count >= 0  # just not an error
