name: Update TOC
on:
  push:
    paths:
      - "**/*.md"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: toc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  toc:
    if: >-
      ${{ github.event_name != 'push' ||
          !contains(github.event.head_commit.message, 'chore: update TOC') }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install doctoc
        run: npm i -g doctoc@2

      - name: Update TOC in README
        run: doctoc README.md --github --maxlevel 3 --notitle

      - name: Commit changes if any
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "toc-bot"
            git config user.email "toc-bot@users.noreply.github.com"
            git commit -am "chore: update TOC"
            git push
          else
            echo "No TOC changes."
          fi